# Generated by Django 2.0.13 on 2022-02-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Edges_name', models.CharField(max_length=200, verbose_name='节点名称')),
                ('Edges_data', models.TextField(verbose_name='节点数据')),
            ],
        ),
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nodes_name', models.CharField(max_length=200, verbose_name='节点名称')),
                ('Nodes_data', models.TextField(verbose_name='节点数据')),
                ('Nodes_id', models.ManyToManyField(to='Test.Edges')),
            ],
        ),
    ]
